import '../../../test-setup';
import { TestBed } from '@angular/core/testing';
import { SchemaFormFactory, type FormMode } from './schema-form-factory.service';
import { FetchlaneService } from './fetchlane.service';
import { LoggerFactory } from '@theredhead/foundation';
import type { ColumnInfo, FullTableSchema, ForeignKeyInfo } from '../models';

// ── Helpers ──────────────────────────────────────────────────────────

function makeColumn(overrides: Partial<ColumnInfo> = {}): ColumnInfo {
  return {
    column_name: 'col',
    data_type: 'character varying',
    udt_name: 'varchar',
    is_nullable: true,
    column_default: null,
    is_identity: false,
    identity_generation: null,
    character_maximum_length: null,
    numeric_precision: null,
    numeric_scale: null,
    ordinal_position: 1,
    ...overrides,
  };
}

function makeSchema(
  columns: ColumnInfo[],
  overrides: Partial<FullTableSchema> = {},
): FullTableSchema {
  return {
    table_name: 'test_table',
    table_schema: 'public',
    table_type: 'BASE TABLE',
    columns,
    constraints: [
      {
        constraint_name: 'test_table_pkey',
        constraint_type: 'PRIMARY KEY',
        columns: ['id'],
        referenced_table_schema: null,
        referenced_table: null,
        referenced_columns: [],
        update_rule: null,
        delete_rule: null,
      },
    ],
    indexes: [],
    ...overrides,
  };
}

// ── Setup ────────────────────────────────────────────────────────────

describe('SchemaFormFactory', () => {
  let factory: SchemaFormFactory;
  let fetchlaneStub: { extractForeignKeys: ReturnType<typeof vi.fn> };

  beforeEach(() => {
    fetchlaneStub = {
      extractForeignKeys: vi.fn().mockReturnValue([]),
    };

    TestBed.configureTestingModule({
      providers: [SchemaFormFactory, { provide: FetchlaneService, useValue: fetchlaneStub }],
    });

    factory = TestBed.inject(SchemaFormFactory);
  });

  // ── buildFormSchema basics ─────────────────────────────────────────

  describe('buildFormSchema', () => {
    it('should produce a FormSchema with correct id and title for add mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          is_identity: true,
          identity_generation: 'BY DEFAULT',
        }),
        makeColumn({ column_name: 'name', column_default: null, is_nullable: false }),
      ]);

      const result = factory.buildFormSchema(schema, 'add');

      expect(result.id).toBe('test_table-add');
      expect(result.title).toBe('Add test_table');
      expect(result.groups).toHaveLength(1);
      expect(result.groups[0].id).toBe('main');
    });

    it('should produce correct title for edit mode', () => {
      const schema = makeSchema([
        makeColumn({ column_name: 'id', data_type: 'integer', udt_name: 'int4' }),
      ]);
      const result = factory.buildFormSchema(schema, 'edit');
      expect(result.title).toBe('Edit test_table');
    });
  });

  // ── isAutoGenerated / shouldIncludeField ───────────────────────────

  describe('field inclusion', () => {
    it('should exclude identity columns in add mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          is_identity: true,
          identity_generation: 'BY DEFAULT',
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const result = factory.buildFormSchema(schema, 'add');
      const fieldIds = result.groups[0].fields.map((f) => f.id);

      expect(fieldIds).not.toContain('id');
      expect(fieldIds).toContain('name');
    });

    it('should exclude ALWAYS identity columns in any mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          is_identity: true,
          identity_generation: 'ALWAYS',
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const addResult = factory.buildFormSchema(schema, 'add');
      const editResult = factory.buildFormSchema(schema, 'edit');

      expect(addResult.groups[0].fields.map((f) => f.id)).not.toContain('id');
      expect(editResult.groups[0].fields.map((f) => f.id)).not.toContain('id');
    });

    it('should exclude columns with nextval default in add mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          column_default: "nextval('test_table_id_seq'::regclass)",
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const result = factory.buildFormSchema(schema, 'add');
      expect(result.groups[0].fields.map((f) => f.id)).not.toContain('id');
    });

    it('should exclude columns with auto_increment default in add mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          column_default: 'auto_increment',
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const result = factory.buildFormSchema(schema, 'add');
      expect(result.groups[0].fields.map((f) => f.id)).not.toContain('id');
    });

    it('should include nextval columns in edit mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          column_default: "nextval('test_table_id_seq'::regclass)",
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const result = factory.buildFormSchema(schema, 'edit');
      expect(result.groups[0].fields.map((f) => f.id)).toContain('id');
    });

    it('should include plain integer PK (no auto-generation) in add mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          is_nullable: false,
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const result = factory.buildFormSchema(schema, 'add');
      expect(result.groups[0].fields.map((f) => f.id)).toContain('id');
    });
  });

  // ── readonly in edit mode ──────────────────────────────────────────

  describe('readonly fields', () => {
    it('should make PK readonly in edit mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          is_nullable: false,
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const result = factory.buildFormSchema(schema, 'edit');
      const idField = result.groups[0].fields.find((f) => f.id === 'id')!;
      const nameField = result.groups[0].fields.find((f) => f.id === 'name')!;

      expect(idField.enabledWhen).toBeDefined();
      expect(nameField.enabledWhen).toBeUndefined();
    });

    it('should make auto-generated columns readonly in edit mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          column_default: "nextval('seq')",
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const result = factory.buildFormSchema(schema, 'edit');
      const idField = result.groups[0].fields.find((f) => f.id === 'id')!;

      expect(idField.enabledWhen).toBeDefined();
    });

    it('should not make PK readonly in add mode', () => {
      const schema = makeSchema([
        makeColumn({
          column_name: 'id',
          data_type: 'integer',
          udt_name: 'int4',
          is_nullable: false,
        }),
        makeColumn({ column_name: 'name', ordinal_position: 2 }),
      ]);

      const result = factory.buildFormSchema(schema, 'add');
      const idField = result.groups[0].fields.find((f) => f.id === 'id')!;

      expect(idField.enabledWhen).toBeUndefined();
    });
  });

  // ── mapComponent ───────────────────────────────────────────────────

  describe('component mapping', () => {
    const cases: [Partial<ColumnInfo>, string][] = [
      [{ data_type: 'integer', udt_name: 'int4' }, 'number'],
      [{ data_type: 'bigint', udt_name: 'int8' }, 'number'],
      [{ data_type: 'smallint', udt_name: 'int2' }, 'number'],
      [{ data_type: 'numeric', udt_name: 'numeric' }, 'number'],
      [{ data_type: 'decimal', udt_name: 'numeric' }, 'number'],
      [{ data_type: 'real', udt_name: 'float4' }, 'number'],
      [{ data_type: 'double precision', udt_name: 'float8' }, 'number'],
      [{ data_type: 'boolean', udt_name: 'bool' }, 'checkbox'],
      [{ data_type: 'date', udt_name: 'date' }, 'date'],
      [{ data_type: 'timestamp without time zone', udt_name: 'timestamp' }, 'datetime'],
      [{ data_type: 'time', udt_name: 'time' }, 'time'],
      [{ data_type: 'text', udt_name: 'text' }, 'textarea'],
      [
        { data_type: 'character varying', udt_name: 'varchar', character_maximum_length: 500 },
        'textarea',
      ],
      [
        { data_type: 'character varying', udt_name: 'varchar', character_maximum_length: 100 },
        'text',
      ],
      [{ data_type: 'character varying', udt_name: 'varchar' }, 'text'],
    ];

    it.each(cases)('should map %o to "%s"', (colOverrides, expectedComponent) => {
      const col = makeColumn({ column_name: 'field', ...colOverrides });
      const schema = makeSchema([col], {
        constraints: [],
      });

      const result = factory.buildFormSchema(schema, 'add');
      expect(result.groups[0].fields[0].component).toBe(expectedComponent);
    });
  });

  // ── validation rules ───────────────────────────────────────────────

  describe('validation', () => {
    it('should add required rule for NOT NULL columns without default', () => {
      const schema = makeSchema(
        [makeColumn({ column_name: 'title', is_nullable: false, column_default: null })],
        { constraints: [] },
      );

      const result = factory.buildFormSchema(schema, 'add');
      const rules = result.groups[0].fields[0].validation ?? [];

      expect(rules).toEqual(
        expect.arrayContaining([expect.objectContaining({ type: 'required' })]),
      );
    });

    it('should not add required rule for identity columns', () => {
      const schema = makeSchema(
        [
          makeColumn({
            column_name: 'id',
            is_nullable: false,
            is_identity: true,
            identity_generation: 'BY DEFAULT',
            data_type: 'integer',
            udt_name: 'int4',
          }),
        ],
        { constraints: [] },
      );

      const result = factory.buildFormSchema(schema, 'edit');
      const rules = result.groups[0].fields[0].validation ?? [];

      expect(rules).not.toEqual(
        expect.arrayContaining([expect.objectContaining({ type: 'required' })]),
      );
    });

    it('should not add required rule for nullable columns', () => {
      const schema = makeSchema([makeColumn({ column_name: 'notes', is_nullable: true })], {
        constraints: [],
      });

      const result = factory.buildFormSchema(schema, 'add');
      const rules = result.groups[0].fields[0].validation ?? [];

      expect(rules).not.toEqual(
        expect.arrayContaining([expect.objectContaining({ type: 'required' })]),
      );
    });

    it('should not add required rule when column has a default', () => {
      const schema = makeSchema(
        [makeColumn({ column_name: 'status', is_nullable: false, column_default: "'active'" })],
        { constraints: [] },
      );

      const result = factory.buildFormSchema(schema, 'add');
      const rules = result.groups[0].fields[0].validation ?? [];

      expect(rules).not.toEqual(
        expect.arrayContaining([expect.objectContaining({ type: 'required' })]),
      );
    });

    it('should add maxLength rule for varchar columns', () => {
      const schema = makeSchema(
        [makeColumn({ column_name: 'name', character_maximum_length: 160 })],
        { constraints: [] },
      );

      const result = factory.buildFormSchema(schema, 'add');
      const rules = result.groups[0].fields[0].validation ?? [];

      expect(rules).toEqual(
        expect.arrayContaining([
          expect.objectContaining({ type: 'maxLength', params: { max: 160 } }),
        ]),
      );
    });

    it('should not set maxlength in config (only in validation)', () => {
      const schema = makeSchema(
        [makeColumn({ column_name: 'name', character_maximum_length: 160 })],
        { constraints: [] },
      );

      const result = factory.buildFormSchema(schema, 'add');
      const config = result.groups[0].fields[0].config ?? {};

      expect(config).not.toHaveProperty('maxlength');
    });
  });

  // ── FK placeholder ─────────────────────────────────────────────────

  describe('foreign key config', () => {
    it('should set placeholder for FK columns', () => {
      const fks: ForeignKeyInfo[] = [
        {
          constraintName: 'fk_artist',
          column: 'artist_id',
          referencedTable: 'artist',
          referencedColumn: 'artist_id',
        },
      ];
      fetchlaneStub.extractForeignKeys.mockReturnValue(fks);

      const schema = makeSchema(
        [makeColumn({ column_name: 'artist_id', data_type: 'integer', udt_name: 'int4' })],
        { constraints: [] },
      );

      const result = factory.buildFormSchema(schema, 'add');
      const config = result.groups[0].fields[0].config;

      expect(config).toEqual(expect.objectContaining({ placeholder: 'artist.artist_id' }));
    });
  });

  // ── humanize ───────────────────────────────────────────────────────

  describe('field titles', () => {
    it('should humanize snake_case column names', () => {
      const schema = makeSchema([makeColumn({ column_name: 'first_name' })], { constraints: [] });

      const result = factory.buildFormSchema(schema, 'add');
      expect(result.groups[0].fields[0].title).toBe('First Name');
    });

    it('should humanize camelCase column names', () => {
      const schema = makeSchema([makeColumn({ column_name: 'firstName' })], { constraints: [] });

      const result = factory.buildFormSchema(schema, 'add');
      expect(result.groups[0].fields[0].title).toBe('First Name');
    });
  });
});
